apiVersion: skydive-group.example.com/v1
kind: Skydive
metadata:
  name: skydive-sample
spec:
  namespace: skydive
  enable:
    analyzer: true
    agents: true
    route: false
  agents:
    daemonSet:
      env:
        - name: SKYDIVE_ANALYZERS
          value: $(SKYDIVE_ANALYZER_SERVICE_HOST):$(SKYDIVE_ANALYZER_SERVICE_PORT_API)
        - name: SKYDIVE_LOGGING_LEVEL
          value: ERROR
  analyzer:
    deployment:
      env:
        - name: SKYDIVE_LOGGING_LEVEL
          value: ERROR
